version: "3.0"

services:

  nginx:
      container_name: "nginx"
      build:
        context: nginx
      volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/access.log:/var/log/nginx/access.log
      # - ./nginx/error.log:/var/log/nginx/error.log
      restart:
        on-failure
      networks:
        - gateway
      ports:
        - 80:80
      depends_on:
        - server1
        - server2

  server1:
    container_name: server1
    networks:
      - gateway
    env_file:
      - ./flask/.env
    build : 
      context: flask
    volumes:
      - ./flask:/app
    command: 
      gunicorn -w 2 --chdir /app app:app -b :8080  --log-level error --reload

  server2:
    container_name: server2
    networks:
      - gateway
    env_file:
      - ./flask/.env
    build : 
      context: flask
    volumes:
      - ./flask:/app
    command: 
      gunicorn -w 2 --chdir /app app:app -b :8080  --log-level error --reload

networks:
  gateway: {}
