version: "3.0"

services:

  server:
    container_name: server
    networks:
      - gateway
    env_file:
      - ./flask/.env
    build : flask
    volumes:
      - ./flask:/app
    ports:
        - 5000:8080


  

networks:
  gateway: {}
